In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt
from scipy.signal import convolve2d

In [3]:
I = np.array ([[20, 21, 23, 24, 24, 24],
               [23, 22, 24, 25, 26, 26],
               [22, 23, 25, 28, 30, 31],
               [25, 28, 29, 30, 30, 31],
               [26, 29, 30, 31, 35, 35],
               [28, 30, 31, 31, 33, 33]])

H = np.array ([[0, 1, 0],
               [1, 4, 1],
               [0, 1, 1]]) / 8

In [4]:
Y = convolve2d(I, H, 'same', 'symm')

In [5]:
print(Y)

[[23.    23.75  25.625 26.875 27.25  27.25 ]
 [24.875 24.875 26.5   28.125 29.125 29.375]
 [25.5   26.5   28.25  30.75  32.5   33.5  ]
 [27.875 30.    31.5   32.875 34.25  35.125]
 [29.625 31.875 33.5   34.875 37.375 38.   ]
 [31.25  33.    34.375 35.    36.875 37.625]]
